global:
  name: productpage
  version: v1.1.11

app:
  image: docker.io/istio/examples-bookinfo-productpage-v1:1.15.0
  imagePullPolicy: IfNotPresent
  containerPort: 9080
  replicaCount: 1

serviceAccount:
  name: bookinfo-productpage

spinnaker:
  max_version_history: "2"
