global:
  name: reviews
  version: reviews-2

app:
  image: docker.io/istio/examples-bookinfo-reviews-v2:1.15.0
  imagePullPolicy: IfNotPresent
  containerPort: 9080
  replicaCount: 2

serviceAccount:
  name: bookinfo-reviews

spinnaker:
  max_version_history: "2"
