global:
  name: reviews
  version: v222223333

app:
  image: docker.io/istio/examples-bookinfo-reviews-v3:1.15.0
  imagePullPolicy: IfNotPresent
  containerPort: 9080
  replicaCount: 3

serviceAccount:
  name: bookinfo-reviews

spinnaker:
  max_version_history: "2"
