global:
  name: reviews
  version: v1.1.3

app:
  image: docker.io/istio/examples-bookinfo-ratings-v1:1.15.0
  imagePullPolicy: IfNotPresent
  containerPort: 9080
  replicaCount: 3

serviceAccount:
  name: bookinfo-reviews

spinnaker:
  max_version_history: "2"
